name: order_app
description: "Order of Monich."

publish_to: "none" # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  camera: ^0.11.3
  charset_converter: ^2.3.0
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  contacts_service: ^0.6.3
  cryptography: ^2.9.0 # для шифрования Web Push
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.2.0
  firebase_messaging: ^16.1.1
  image: ^4.5.4 # совместима с pdf
  image_picker: ^1.2.1
  intl: ^0.20.2
  google_sign_in: ^7.2.0
  googleapis: ^15.0.0 # Для работы с Google API
  googleapis_auth: ^2.0.0 # Для аутентификации сервисных аккаунтов в Google
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0 # Если используется HTTP-клиент
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  share_plus: ^7.2.1
  shared_preferences: ^2.5.4
  table_calendar: ^3.2.0
  telephony: ^0.1.4 # для получения номера телефона (Android)
  url_launcher: ^6.3.2

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # 🔥 VARIABLE FONTS — оптимально для Web/PWA
  fonts:
    # Playfair Display (заголовки, премиум-стиль)
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic
    # Lora (основной текст, читаемость)
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-VariableFont_wght.ttf
        - asset: assets/fonts/Lora-Italic-VariableFont_wght.ttf
          style: italic

  uses-material-design: true
  assets:
    - assets/images/auth/
    - assets/images/web/
    - assets/images/products/
    - assets/fonts/PlayfairDisplay-Regular.ttf
    - assets/fonts/Lora-Regular.ttf
    - assets/texts/offer.txt
