import 'dart:io';
import 'dart:convert';

void main() {
  print('🔄 Генерация asset-файлов...');

  // Создаем папку generated если её нет
  final generatedDir = Directory('lib/generated');
  if (!generatedDir.existsSync()) {
    generatedDir.createSync(recursive: true);
  }

  // Генерируем auth_assets.dart
  _generateAuthAssets();

  // Здесь можно добавить другие генераторы
  // _generateProductAssets();

  print('✅ Генерация завершена');
}

void _generateAuthAssets() {
  final authDir = Directory('assets/images/auth');

  if (!authDir.existsSync()) {
    print('⚠️ Папка assets/images/auth не найдена, создаем пустой файл');
    _writeAuthAssetsFile([]);
    return;
  }

  // Собираем все webp файлы, кроме logo
  final backgroundFiles = authDir
      .listSync()
      .where((file) =>
          file is File &&
          file.path.endsWith('.webp') &&
          !file.path.contains('logo'))
      .map((file) => 'assets/images/auth/${file.path.split('/').last}')
      .toList();

  // Сортируем для стабильности
  backgroundFiles.sort();

  print('📸 Найдено фоновых изображений: ${backgroundFiles.length}');
  _writeAuthAssetsFile(backgroundFiles);
}

void _writeAuthAssetsFile(List<String> backgrounds) {
  final code = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_assets.dart

class AuthAssets {
  /// Список всех фоновых изображений для экрана авторизации
  static const List<String> backgrounds = ${jsonEncode(backgrounds)};
  
  /// Логотип приложения
  static const String logo = 'assets/images/auth/logo.webp';
  
  /// Проверяет, существует ли логотип в assets
  static bool get hasLogo => true; // Логотип всегда должен быть
  
  /// Количество фоновых изображений
  static int get backgroundCount => backgrounds.length;
  
  /// Получить фоновое изображение по индексу (с защитой от выхода за границы)
  static String getBackground(int index) {
    if (backgrounds.isEmpty) return '';
    return backgrounds[index % backgrounds.length];
  }
}
''';

  File('lib/generated/auth_assets.dart').writeAsStringSync(code);
  print('📄 Сгенерирован lib/generated/auth_assets.dart');
}
